(() => {
 const picker=document.querySelector('#photo-picker'), dialog=document.querySelector('#photo-dialog'), canvas=document.querySelector('#photo-canvas'), zoom=document.querySelector('#photo-zoom'), feedback=document.querySelector('#photo-feedback'), status=document.querySelector('#crop-status'), save=document.querySelector('#save-photo');
 const csrf=document.querySelector('[name=csrf]').value;
 let name='',bitmap=null,scale=1,x=0,y=0,drag=null,busy=false,opener=null;
 function pick(who){name=who;opener=document.activeElement;document.querySelectorAll('.person-menu:popover-open').forEach(p=>p.hidePopover());picker.value='';picker.click();}
 function draw(){if(!bitmap)return;const size=256,ratio=Math.max(size/bitmap.width,size/bitmap.height)*scale,w=bitmap.width*ratio,h=bitmap.height*ratio;x=Math.max((size-w)/2,Math.min((w-size)/2,x));y=Math.max((size-h)/2,Math.min((h-size)/2,y));const ctx=canvas.getContext('2d');ctx.clearRect(0,0,size,size);ctx.drawImage(bitmap,(size-w)/2+x,(size-h)/2+y,w,h);}
 document.querySelector('#new-person').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#new-person-name');if(input.reportValidity())pick(input.value.trim());});
 document.addEventListener('click',async e=>{const pickButton=e.target.closest('[data-pick]');if(pickButton){pick(pickButton.dataset.pick);return;}const remove=e.target.closest('[data-remove]');if(!remove)return;remove.disabled=true;try{await upload(remove.dataset.remove,'remove_photo');location.assign('/settings?saved=1');}catch(error){remove.disabled=false;feedback.textContent=error.message;document.querySelectorAll('.person-menu:popover-open').forEach(p=>p.hidePopover());}});
 document.querySelectorAll('.person-menu').forEach(menu=>menu.addEventListener('toggle',()=>{if(!menu.matches(':popover-open'))return;const button=document.querySelector('[popovertarget="'+menu.id+'"]'),r=button.getBoundingClientRect();menu.style.left=Math.max(12,Math.min(r.right-menu.offsetWidth,innerWidth-menu.offsetWidth-12))+'px';menu.style.top=Math.max(12,Math.min(r.bottom+6,innerHeight-menu.offsetHeight-12))+'px';}));
 picker.addEventListener('change',async()=>{const file=picker.files[0];if(!file)return;feedback.textContent='';status.textContent='';if(file.size>4*1024*1024){feedback.textContent='Choose an image under 4 MiB.';return;}try{const image=await createImageBitmap(file);if(image.width>4096||image.height>4096||image.width*image.height>16000000){image.close();throw Error('Choose an image up to 4,096 pixels per side and 16 megapixels.');}bitmap?.close();bitmap=image;scale=1;x=0;y=0;zoom.value='1';draw();document.querySelector('#photo-for').textContent=name;if(!dialog.open)dialog.showModal();}catch(error){feedback.textContent=error.message.startsWith('Choose')?error.message:'Your browser could not open that image. Try WebP, AVIF, PNG or JPEG.';if(dialog.open)status.textContent=feedback.textContent;}});
 zoom.addEventListener('input',()=>{scale=Number(zoom.value);draw();});canvas.addEventListener('pointerdown',e=>{if(busy)return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;const factor=256/canvas.getBoundingClientRect().width;x+=(e.clientX-drag.x)*factor;y+=(e.clientY-drag.y)*factor;drag={x:e.clientX,y:e.clientY};draw();});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
 canvas.tabIndex=0;canvas.addEventListener('keydown',e=>{const moves={ArrowLeft:[-8,0],ArrowRight:[8,0],ArrowUp:[0,-8],ArrowDown:[0,8]};if(moves[e.key]){e.preventDefault();x+=moves[e.key][0];y+=moves[e.key][1];draw();}});
 async function upload(author,action,blob){const form=new FormData();form.set('csrf',csrf);form.set('name',author);form.set('action',action);if(blob)form.set('photo',blob,'avatar.png');const response=await fetch('/settings',{method:'POST',body:form});if(!response.ok){const doc=new DOMParser().parseFromString(await response.text(),'text/html');throw Error(doc.querySelector('.settings-feedback.error')?.textContent||'Could not save the photo. Please try again.');}}
 save.addEventListener('click',async()=>{if(!bitmap||busy)return;busy=true;save.disabled=true;save.textContent='Saving…';document.querySelector('#cancel-photo').disabled=true;document.querySelector('#choose-another').disabled=true;try{const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Could not prepare that photo. Try another image.');await upload(name,'photo',blob);location.assign('/settings?saved=1');}catch(error){status.textContent=error.message;busy=false;save.disabled=false;save.textContent='Save photo';document.querySelector('#cancel-photo').disabled=false;document.querySelector('#choose-another').disabled=false;}});
 document.querySelector('#cancel-photo').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{bitmap?.close();bitmap=null;opener?.focus({preventScroll:true});});document.querySelector('#choose-another').onclick=()=>{picker.value='';picker.click();};
})();

(() => {
 const dialog=document.querySelector('#key-dialog'), primary=document.querySelector('#key-primary'), revoke=document.querySelector('#key-revoke'), feedback=document.querySelector('#key-feedback'), result=document.querySelector('#key-result'), secret=document.querySelector('#key-secret'), snippet=document.querySelector('#key-snippet');
 let name='',active=false,busy=false,changed=false,confirmAction='';
 const date=value=>value?new Date(value).toLocaleString():'';
 function setup(key){return document.querySelector('#agent-setup-guide').value.replace(/\{\{(ORIGIN|AUTHOR|KEY|OWNER)\}\}/g,(_,field)=>({ORIGIN:location.origin,AUTHOR:name,KEY:key,OWNER:document.querySelector('#agent-setup-guide').dataset.owner})[field]);}
 function controls(){primary.textContent=active?'Rotate key':'Create key';revoke.hidden=!active;document.querySelector('#key-warning').textContent=active?'Rotating or revoking stops the current key from working. Update the agent after rotating.':'';}
 function openKey(button){name=button.dataset.keyName;active=button.dataset.keyActive==='true';document.querySelector('#key-person').textContent=name;document.querySelector('#key-history').textContent=active?'Created '+date(button.dataset.keyCreated)+'. '+(button.dataset.keyUsed?'Last used '+date(button.dataset.keyUsed)+'.':'Not used yet.'):'No active publishing key.';result.hidden=true;snippet.value=setup('[Load your existing Cairn key from your secret store, or create one below]');feedback.textContent='';confirmAction='';controls();dialog.showModal();}
 document.querySelectorAll('[data-key-name]').forEach(button=>button.onclick=()=>openKey(button));
 document.querySelector('#new-person-key').onclick=()=>{const input=document.querySelector('#new-person-name');if(!input.reportValidity()||!input.value.trim())return;const existing=[...document.querySelectorAll('[data-key-name]')].find(b=>b.dataset.keyName===input.value.trim());openKey(existing||{dataset:{keyName:input.value.trim(),keyActive:'false'}});};
 async function change(action){if(busy)return;if(action!=='key_create'&&confirmAction!==action){confirmAction=action;feedback.textContent=action==='key_rotate'?'The old key will stop working immediately. Click Rotate key again to continue.':'The agent will lose publishing access. Click Revoke key again to continue.';return;}busy=true;primary.disabled=revoke.disabled=true;document.querySelector('#key-close').disabled=true;feedback.textContent='Updating key…';try{const form=new URLSearchParams({csrf:document.querySelector('[name=csrf]').value,name,action});const response=await fetch('/settings',{method:'POST',body:form});if(!response.ok)throw Error(await response.text());const data=await response.json();changed=true;active=!!data.key;confirmAction='';controls();result.hidden=!active;secret.value=data.key;snippet.value=setup(data.key||'[Load your existing Cairn key from your secret store]');document.querySelector('#key-history').textContent=active?'Created just now. Not used yet.':'Publishing access revoked.';feedback.textContent=active?'Key ready. Save it in the agent’s secret store before closing.':'Key revoked. Existing pages are unchanged.';}catch(error){feedback.textContent=error.message||'Could not update the key. Try again.';}finally{busy=false;primary.disabled=revoke.disabled=false;document.querySelector('#key-close').disabled=false;}}
 primary.onclick=()=>change(active?'key_rotate':'key_create');revoke.onclick=()=>change('key_revoke');
 async function copy(field){try{if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(field.value);}else{field.focus();field.select();if(!document.execCommand('copy'))throw Error();}feedback.textContent='Copied.';}catch{field.focus();field.select();feedback.textContent='Select and copy the text above.';}}
 document.querySelector('#key-copy').onclick=()=>copy(secret);document.querySelector('#snippet-copy').onclick=()=>copy(snippet);document.querySelector('#key-close').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{secret.value='';snippet.value='';if(changed)location.assign('/settings');});
})();
